### ISSUE TITLE
Determine `MemoryInfo.TotalPhysicalBytes` on Windows

### ISSUE THREAD

**Issue by jaypipes** [jaypipes/ghw#185]
We should be able to determine the total amount of physical memory attached to the hardware on Windows by summing the size of the `Win32_MemoryBank.Size` WMI table fields.

See https://github.com/jaypipes/ghw/pull/171#issuecomment-597082409

**Comment by jaypipes** [comment]
This is now being done:

```
PS C:\Users\jaypi\go\src\github.com\jaypipes\ghw> go run .\cmd\ghwc\main.go memory -fyaml                                                                                                                                                                                      memory:
  modules:
  - label: P0 CHANNEL A
    location: DIMM 1
    serial_number: 511216B4
    size_bytes: 8589934592
    vendor: Kingston
  - label: P0 CHANNEL B
    location: DIMM 1
    serial_number: 5212D9B3
    size_bytes: 8589934592
    vendor: Kingston
  supported_page_sizes: null
  total_physical_bytes: 17179869184
  total_usable_bytes: 17125675008
```
